# Generated by Django 2.2 on 2019-04-24 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('isValid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentForDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('isvalid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='')])),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='')])),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')])),
                ('lastName', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')])),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')])),
                ('password', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(regex='')])),
                ('isDesigner', models.BooleanField()),
                ('tag', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='RateForTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag')),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='RateForDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_designer', to='blog.Designer')),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_designer', to='blog.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='RateForDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_design', to='blog.Design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_design', to='blog.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='DesignerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_records', to='blog.Designer')),
            ],
        ),
        migrations.AddField(
            model_name='designer',
            name='comments',
            field=models.ManyToManyField(related_name='Designer1', through='blog.CommentForDesigner', to='blog.UserAccount'),
        ),
        migrations.AddField(
            model_name='designer',
            name='rates',
            field=models.ManyToManyField(related_name='Designer2', through='blog.RateForDesigner', to='blog.UserAccount'),
        ),
        migrations.AddField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='blog.UserAccount'),
        ),
        migrations.AddField(
            model_name='design',
            name='comments',
            field=models.ManyToManyField(through='blog.CommentForDesign', to='blog.UserAccount'),
        ),
        migrations.AddField(
            model_name='design',
            name='designer',
            field=models.ManyToManyField(related_name='designs', to='blog.Designer'),
        ),
        migrations.AddField(
            model_name='design',
            name='tag',
            field=models.ManyToManyField(related_name='designs', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='commentfordesigner',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_designer', to='blog.Designer'),
        ),
        migrations.AddField(
            model_name='commentfordesigner',
            name='userAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_designer', to='blog.UserAccount'),
        ),
        migrations.AddField(
            model_name='commentfordesign',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_design', to='blog.Design'),
        ),
        migrations.AddField(
            model_name='commentfordesign',
            name='userAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_design', to='blog.UserAccount'),
        ),
        migrations.CreateModel(
            name='CollectionOfDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('collectionPicture', models.ImageField(upload_to=None)),
                ('designer', models.ManyToManyField(to='blog.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionOfDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('collPic', models.ImageField(upload_to=None)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_of_design', to='blog.UserAccount')),
            ],
        ),
    ]
